=== apk998/hospital-db/src/main/resources/assignment/prescription.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="prescriptions" type="Prescriptions"/>
    <xs:complexType name="Prescriptions">
        <xs:sequence>
            <xs:element name="prescription" type="Prescription" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="Prescription">
        <xs:sequence>
            <xs:element name="id" type="xs:int"/>
            <xs:element name="prescription_id" type="xs:int"/>
            <xs:element name="medication_name" type="xs:string"/>
            <xs:element name="prescription_date" type="xs:date"/>
            <xs:element name="appt_id" type="xs:int"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== apk998/hospital-db/src/main/resources/assignment/prescription.xml
<prescriptions xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:noNamespaceSchemaLocation="prescription.xsd">
    <prescription>
        <id>1</id>
        <prescription_id>3291</prescription_id>
        <medication_name>Aspirin</medication_name>
        <prescription_date>2024-01-03</prescription_date>
        <appt_id>9052</appt_id>
    </prescription>
    <prescription>
        <id>2</id>
        <prescription_id>5037</prescription_id>
        <medication_name>Doxycycline</medication_name>
        <prescription_date>2024-01-08</prescription_date>
        <appt_id>11208</appt_id>
    </prescription>
    <prescription>
        <id>3</id>
        <prescription_id>5584</prescription_id>
        <medication_name>Lamotrigine</medication_name>
        <prescription_date>2024-01-08</prescription_date>
        <appt_id>11317</appt_id>
    </prescription>
</prescriptions>
